import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://ecomrag.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    ChatbotSettings: {
      type: "hasOne",
      child: { model: "chatbotSettings", belongsToField: "shop" },
      storageKey: "oHcOaYWxmq1q::QWHXdPeTQBrW",
    },
    Plan: {
      type: "string",
      default: "Free",
      storageKey: "5OeIavcMx76n::QnosEDzWaieg",
    },
    chatSessionsLimit: {
      type: "number",
      default: 600,
      storageKey: "48Gbtk1Vo4y8::vZd6HzueQgrI",
    },
    confirmationUrl: {
      type: "url",
      storageKey: "z8OIVL7143m6::glJL4fho7fXp",
    },
    plan: {
      type: "hasOne",
      child: { model: "plan", belongsToField: "shop" },
      storageKey: "ggIrrylHbrMB::AVBgr26grAjt",
    },
    productImageSyncCount: {
      type: "number",
      default: 0,
      storageKey: "DDFESExz4rbC::HenF-WradI2m",
    },
    productImageSyncLimit: {
      type: "number",
      default: 300,
      storageKey: "a_owZfutVrRF::9JCBzEgVSr_i",
    },
    productSyncCount: {
      type: "number",
      default: 0,
      storageKey: "4hCMsycQ_H4l::MdIQWsjgQ5n1",
    },
    productSyncLimit: {
      type: "number",
      default: 100,
      storageKey: "ssmmKtInAzIH::dKEYU7hQIee6",
    },
    subscriptionId: {
      type: "string",
      storageKey: "faEwU_uaXbol::52AONq1l9vOS",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "checkoutApiSupported",
      "city",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "domain",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderLineItems",
      "orders",
      "passwordEnabled",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "productImages",
      "products",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
